In [3]:
import networkx as nx 

In [ ]:
G = nx.DiGraph()   # or MultiGraph, etc
G.add_path([0,1])
H = G.to_directed()
H.edges()
[(0, 1), (1, 0)]
G2 = H.to_undirected()
G2.edges()
[(0, 1)]

In [34]:
G=nx.Graph()
G.add_weighted_edges_from([(1,2,0.125),(1,3,0.75),(2,4,1.2),(3,4,0.375),(2,1,5),(3,1,10)])

{1: {2: {'weight': 5}, 3: {'weight': 10}},
 2: {1: {'weight': 5}, 4: {'weight': 1.2}},
 3: {1: {'weight': 10}, 4: {'weight': 0.375}},
 4: {2: {'weight': 1.2}, 3: {'weight': 0.375}}}

In [23]:
A = nx.to_numpy_matrix(G = G,nodelist=G.nodes(),weight='weight')

In [24]:
A

matrix([[  0.   ,   0.125,   0.75 ,   0.   ],
        [  5.   ,   0.   ,   0.   ,   1.2  ],
        [ 10.   ,   0.   ,   0.   ,   0.375],
        [  0.   ,   0.   ,   0.   ,   0.   ]])

In [25]:
A.T

matrix([[  0.   ,   5.   ,  10.   ,   0.   ],
        [  0.125,   0.   ,   0.   ,   0.   ],
        [  0.75 ,   0.   ,   0.   ,   0.   ],
        [  0.   ,   1.2  ,   0.375,   0.   ]])

In [27]:
M = A + A.T

In [32]:
M

matrix([[  0.   ,   5.125,  10.75 ,   0.   ],
        [  5.125,   0.   ,   0.   ,   1.2  ],
        [ 10.75 ,   0.   ,   0.   ,   0.375],
        [  0.   ,   1.2  ,   0.375,   0.   ]])

G2.to_directed().edge

In [30]:
G2 = nx.from_numpy_matrix(M)

In [31]:
G2.edge

{0: {1: {'weight': 5.125}, 2: {'weight': 10.75}},
 1: {0: {'weight': 5.125}, 3: {'weight': 1.2}},
 2: {0: {'weight': 10.75}, 3: {'weight': 0.375}},
 3: {1: {'weight': 1.2}, 2: {'weight': 0.375}}}

In [33]:
G2.is_directed()

False